import type { OpcaoDeCodigo } from './types'

// Os códigos espelham o quadro de RH de `src/assets/rh/rh.jsonl`, a mesma base
// histórica que a simulação percorre. A api não expõe um endpoint de domínio
// para loja, marca e cargo, então a lista vive aqui até que exista um.

export const opcoesDeLoja: readonly OpcaoDeCodigo[] = [
  { valor: '1', rotulo: 'LOJA-1' },
  { valor: '2', rotulo: 'LOJA-2' },
  { valor: '3', rotulo: 'LOJA-3' },
  { valor: '4', rotulo: 'LOJA-4' },
  { valor: '5', rotulo: 'LOJA-5' },
  { valor: '6', rotulo: 'LOJA-6' },
  { valor: '7', rotulo: 'LOJA-7' },
  { valor: '8', rotulo: 'LOJA-8' },
  { valor: '9', rotulo: 'LOJA-9' },
  { valor: '10', rotulo: 'LOJA-10' },
  { valor: '11', rotulo: 'LOJA-11' },
  { valor: '12', rotulo: 'LOJA-12' },
  { valor: '13', rotulo: 'LOJA-13' },
  { valor: '14', rotulo: 'LOJA-14' },
  { valor: '15', rotulo: 'LOJA-15' },
  { valor: '16', rotulo: 'LOJA-16' },
  { valor: '17', rotulo: 'LOJA-17' },
  { valor: '18', rotulo: 'LOJA-18' },
  { valor: '19', rotulo: 'LOJA-19' },
  { valor: '20', rotulo: 'LOJA-20' },
  { valor: '21', rotulo: 'LOJA-21' },
  { valor: '22', rotulo: 'LOJA-22' },
  { valor: '23', rotulo: 'LOJA-23' },
  { valor: '24', rotulo: 'LOJA-24' },
  { valor: '25', rotulo: 'LOJA-25' },
  { valor: '26', rotulo: 'LOJA-26' },
  { valor: '27', rotulo: 'LOJA-27' },
  { valor: '28', rotulo: 'LOJA-28' },
  { valor: '29', rotulo: 'LOJA-29' },
  { valor: '30', rotulo: 'LOJA-30' },
  { valor: '31', rotulo: 'LOJA-31' },
  { valor: '32', rotulo: 'LOJA-32' },
  { valor: '33', rotulo: 'LOJA-33' },
  { valor: '34', rotulo: 'LOJA-34' },
  { valor: '35', rotulo: 'LOJA-35' },
  { valor: '36', rotulo: 'LOJA-36' },
  { valor: '37', rotulo: 'LOJA-37' },
  { valor: '38', rotulo: 'LOJA-38' },
  { valor: '39', rotulo: 'LOJA-39' },
  { valor: '40', rotulo: 'LOJA-40' },
  { valor: '41', rotulo: 'LOJA-41' },
  { valor: '42', rotulo: 'LOJA-42' },
  { valor: '43', rotulo: 'LOJA-43' },
  { valor: '44', rotulo: 'LOJA-44' },
  { valor: '45', rotulo: 'LOJA-45' },
  { valor: '46', rotulo: 'LOJA-46' },
  { valor: '47', rotulo: 'LOJA-47' },
  { valor: '48', rotulo: 'LOJA-48' },
  { valor: '49', rotulo: 'LOJA-49' },
  { valor: '50', rotulo: 'LOJA-50' },
  { valor: '51', rotulo: 'LOJA-51' },
  { valor: '52', rotulo: 'LOJA-52' },
  { valor: '53', rotulo: 'LOJA-53' },
  { valor: '54', rotulo: 'LOJA-54' },
  { valor: '55', rotulo: 'LOJA-55' },
  { valor: '56', rotulo: 'LOJA-56' },
  { valor: '57', rotulo: 'LOJA-57' },
  { valor: '58', rotulo: 'LOJA-58' },
  { valor: '59', rotulo: 'LOJA-59' },
  { valor: '60', rotulo: 'LOJA-60' },
  { valor: '61', rotulo: 'LOJA-61' },
  { valor: '62', rotulo: 'LOJA-62' },
  { valor: '63', rotulo: 'LOJA-63' },
  { valor: '64', rotulo: 'LOJA-64' },
  { valor: '65', rotulo: 'LOJA-65' },
  { valor: '66', rotulo: 'LOJA-66' },
  { valor: '67', rotulo: 'LOJA-67' },
  { valor: '68', rotulo: 'LOJA-68' },
  { valor: '69', rotulo: 'LOJA-69' },
  { valor: '70', rotulo: 'LOJA-70' },
  { valor: '71', rotulo: 'LOJA-71' },
  { valor: '72', rotulo: 'LOJA-72' },
  { valor: '73', rotulo: 'LOJA-73' },
  { valor: '74', rotulo: 'LOJA-74' },
  { valor: '75', rotulo: 'LOJA-75' },
  { valor: '76', rotulo: 'LOJA-76' },
  { valor: '77', rotulo: 'LOJA-77' },
  { valor: '78', rotulo: 'LOJA-78' },
  { valor: '79', rotulo: 'LOJA-79' },
  { valor: '80', rotulo: 'LOJA-80' },
]

export const opcoesDeMarca: readonly OpcaoDeCodigo[] = [
  { valor: '10', rotulo: 'PRETO (10)' },
  { valor: '20', rotulo: 'BRANCO (20)' },
  { valor: '30', rotulo: 'AZUL (30)' },
  { valor: '40', rotulo: 'VERMELHO (40)' },
  { valor: '50', rotulo: 'AMARELO (50)' },
  { valor: '60', rotulo: 'CINZA (60)' },
]

// O código 150 aparece com duas descrições no quadro de RH; o rótulo mantém as
// duas para que a escolha não pareça excluir uma delas.
export const opcoesDeCargo: readonly OpcaoDeCodigo[] = [
  { valor: '100', rotulo: 'VENDEDOR LOJA (100)' },
  { valor: '150', rotulo: 'GERENTE DE LOJA / GERENTE QUIOSQUE (150)' },
  { valor: '200', rotulo: 'VENDEDOR BALCAO (200)' },
  { valor: '300', rotulo: 'ASSISTENTE DE VENDAS (300)' },
]
